adds WINEPATH and tests under wine .. (TODO: improve tests env selection)

diff --git a/testing/Makefile.in b/testing/Makefile.in
--- a/testing/Makefile.in
+++ b/testing/Makefile.in
@@ -14,6 +14,7 @@
 
 @SET_MAKE@
 
+
 VPATH = @srcdir@
 am__is_gnu_make = { \
   if test -z '$(MAKELEVEL)'; then \
@@ -89,6 +90,12 @@ POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
 target_triplet = @target@
+@HAVE_WINECONSOLE_TRUE@@MINGW_TRUE@am__append_1 = WINEPATH='$(shell winepath -w @MAKESHLIBDIR@);$(shell winepath -w $(shell ${CXX} -print-sysroot)/mingw/lib);$(shell winepath -w $(shell ${CXX} -print-sysroot)/mingw/bin)'
+@HAVE_WINECONSOLE_TRUE@@MINGW_TRUE@am__append_2 = wine
+@HAVE_WINECONSOLE_FALSE@@MINGW_TRUE@am__append_3 = @LIBPATH@="@MAKESHLIBDIR@"
+@HAVE_WINECONSOLE_FALSE@@MINGW_TRUE@am__append_4 = sh -c 'exit 77'
+@MINGW_FALSE@am__append_5 = @LIBPATH@="@MAKESHLIBDIR@"
+bin_PROGRAMS = faketest$(EXEEXT)
 subdir = testing
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/ax_prog_doxygen.m4 \
@@ -99,7 +106,7 @@ am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 DIST_COMMON = $(srcdir)/Makefile.am $(am__DIST_COMMON)
 mkinstalldirs = $(install_sh) -d
 CONFIG_HEADER = $(top_builddir)/include/config.h
-CONFIG_CLEAN_FILES =
+CONFIG_CLEAN_FILES = testing.inc
 CONFIG_CLEAN_VPATH_FILES =
 LIBRARIES = $(noinst_LIBRARIES)
 AR = ar
@@ -117,6 +124,14 @@ libMdsTestBackend_a_LIBADD =
 am_libMdsTestBackend_a_OBJECTS =  \
 	libMdsTestBackend_a-check_backend.$(OBJEXT)
 libMdsTestBackend_a_OBJECTS = $(am_libMdsTestBackend_a_OBJECTS)
+am__installdirs = "$(DESTDIR)$(bindir)"
+PROGRAMS = $(bin_PROGRAMS)
+am_faketest_OBJECTS = faketest-faketest.$(OBJEXT)
+faketest_OBJECTS = $(am_faketest_OBJECTS)
+am__DEPENDENCIES_1 =
+faketest_DEPENDENCIES = $(am__DEPENDENCIES_1)
+faketest_LINK = $(CCLD) $(faketest_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) \
+	$(LDFLAGS) -o $@
 AM_V_P = $(am__v_P_@AM_V@)
 am__v_P_ = $(am__v_P_@AM_DEFAULT_V@)
 am__v_P_0 = false
@@ -149,8 +164,10 @@ AM_V_CCLD = $(am__v_CCLD_@AM_V@)
 am__v_CCLD_ = $(am__v_CCLD_@AM_DEFAULT_V@)
 am__v_CCLD_0 = @echo "  CCLD    " $@;
 am__v_CCLD_1 = 
-SOURCES = $(libMdsTest_a_SOURCES) $(libMdsTestBackend_a_SOURCES)
-DIST_SOURCES = $(libMdsTest_a_SOURCES) $(libMdsTestBackend_a_SOURCES)
+SOURCES = $(libMdsTest_a_SOURCES) $(libMdsTestBackend_a_SOURCES) \
+	$(faketest_SOURCES)
+DIST_SOURCES = $(libMdsTest_a_SOURCES) $(libMdsTestBackend_a_SOURCES) \
+	$(faketest_SOURCES)
 RECURSIVE_TARGETS = all-recursive check-recursive cscopelist-recursive \
 	ctags-recursive dvi-recursive html-recursive info-recursive \
 	install-data-recursive install-dvi-recursive \
@@ -192,7 +209,8 @@ am__define_uniq_tagged_files = \
 ETAGS = etags
 CTAGS = ctags
 DIST_SUBDIRS = $(SUBDIRS)
-am__DIST_COMMON = $(srcdir)/Makefile.in $(top_srcdir)/conf/depcomp
+am__DIST_COMMON = $(srcdir)/Makefile.in $(srcdir)/testing.am \
+	$(srcdir)/testing.inc.in $(top_srcdir)/conf/depcomp
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 am__relativize = \
   dir0=`pwd`; \
@@ -230,8 +248,6 @@ CAMSHR = @CAMSHR@
 CC = @CC@
 CCDEPMODE = @CCDEPMODE@
 CFLAGS = @CFLAGS@
-CHECK_CFLAGS = @CHECK_CFLAGS@
-CHECK_LIBS = @CHECK_LIBS@
 CLOCK_GETTIME_LIB = @CLOCK_GETTIME_LIB@
 CPP = @CPP@
 CPPFLAGS = @CPPFLAGS@
@@ -292,6 +308,8 @@ GLOBUS_LOCATION = @GLOBUS_LOCATION@
 GREP = @GREP@
 HAVE_NOSETESTS = @HAVE_NOSETESTS@
 HAVE_VALGRIND = @HAVE_VALGRIND@
+HAVE_WINE = @HAVE_WINE@
+HAVE_WINECONSOLE = @HAVE_WINECONSOLE@
 HDF5_APS = @HDF5_APS@
 HDF5_INCS = @HDF5_INCS@
 HDF5_LIBS = @HDF5_LIBS@
@@ -480,6 +498,32 @@ top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 uiddir = @uiddir@
 SUBDIRS = backends/check .
+TEST_CFLAGS = -I${top_srcdir}/testing
+TEST_LIBS = -lMdsTestShr @LIBM@ @THREAD@ @LIBRT@
+PY_LOG_COMPILER = $(PYTHON)
+PY_LOG_FLAGS = -v
+
+# not used #
+_tap_py_execute = \
+ import unittest; \
+ import tap; \
+ import os; \
+ import sys; \
+ pt = os.path.dirname(os.path.curdir); \
+ loader = unittest.TestLoader(); \
+ tests = loader.loadTestsFromName(sys.argv[1]); \
+ tr = tap.TAPTestRunner(); \
+ tr.set_stream(1); \
+ tr.run(tests); 
+
+TESTS_ENVIRONMENT = $(am__append_1) $(am__append_3) $(am__append_5)
+LOG_COMPILER = $(am__append_2) $(am__append_4)
+TEST_SUITE_TAP = test-suite.tap
+TEST_BUILD_TAP = test-build.tap
+@PY_TAP_SUPPORT_FALSE@TAP_PY_LOG_COMPILER = sh -c 'exit 77'
+@PY_TAP_SUPPORT_TRUE@TAP_PY_LOG_COMPILER = nosetests
+@PY_TAP_SUPPORT_FALSE@TAP_PY_LOG_FLAGS = 
+@PY_TAP_SUPPORT_TRUE@TAP_PY_LOG_FLAGS = --with-tap --tap-stream
 AM_CFLAGS = -I${top_srcdir}/include $(TARGET_ARCH)
 AM_CXXFLAGS = -I${top_srcdir}/include @CXXFLAGS@ $(TARGET_ARCH)
 
@@ -495,6 +539,9 @@ libMdsTest_a_SOURCES = base_backend.c
 libMdsTestBackend_a_CFLAGS = -I${srcdir}/backends/check $(AM_CFLAGS)
 libMdsTestBackend_a_SOURCES = check_backend.c
 MdsTestShr = @MAKESHLIBDIR@@LIBPRE@MdsTestShr@SHARETYPE@
+faketest_SOURCES = faketest.c
+faketest_CFLAGS = $(TARGET_ARCH) $(TEST_CFLAGS) -L@MAKESHLIBDIR@ $(RPATHLINK),@MAKESHLIBDIR@ 
+faketest_LDADD = -L@MAKESHLIBDIR@ $(TEST_LIBS)
 TEST_SUBDIRS = \
                mdsobjects/python/tests \
                mdslib/testing \
@@ -504,7 +551,7 @@ all: all-recursive
 
 .SUFFIXES:
 .SUFFIXES: .c .o .obj
-$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am  $(am__configure_deps)
+$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am $(srcdir)/testing.am $(am__configure_deps)
 	@for dep in $?; do \
 	  case '$(am__configure_deps)' in \
 	    *$$dep*) \
@@ -524,6 +571,7 @@ Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
 	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
 	esac;
+$(srcdir)/testing.am $(am__empty):
 
 $(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
@@ -533,6 +581,8 @@ $(top_srcdir)/configure: @MAINTAINER_MODE_TRUE@ $(am__configure_deps)
 $(ACLOCAL_M4): @MAINTAINER_MODE_TRUE@ $(am__aclocal_m4_deps)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
 $(am__aclocal_m4_deps):
+testing.inc: $(top_builddir)/config.status $(srcdir)/testing.inc.in
+	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@
 
 clean-noinstLIBRARIES:
 	-test -z "$(noinst_LIBRARIES)" || rm -f $(noinst_LIBRARIES)
@@ -546,6 +596,52 @@ libMdsTestBackend.a: $(libMdsTestBackend_a_OBJECTS) $(libMdsTestBackend_a_DEPEND
 	$(AM_V_at)-rm -f libMdsTestBackend.a
 	$(AM_V_AR)$(libMdsTestBackend_a_AR) libMdsTestBackend.a $(libMdsTestBackend_a_OBJECTS) $(libMdsTestBackend_a_LIBADD)
 	$(AM_V_at)$(RANLIB) libMdsTestBackend.a
+install-binPROGRAMS: $(bin_PROGRAMS)
+	@$(NORMAL_INSTALL)
+	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
+	if test -n "$$list"; then \
+	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
+	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
+	fi; \
+	for p in $$list; do echo "$$p $$p"; done | \
+	sed 's/$(EXEEXT)$$//' | \
+	while read p p1; do if test -f $$p \
+	  ; then echo "$$p"; echo "$$p"; else :; fi; \
+	done | \
+	sed -e 'p;s,.*/,,;n;h' \
+	    -e 's|.*|.|' \
+	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
+	sed 'N;N;N;s,\n, ,g' | \
+	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
+	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
+	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
+	    else { print "f", $$3 "/" $$4, $$1; } } \
+	  END { for (d in files) print "f", d, files[d] }' | \
+	while read type dir files; do \
+	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
+	    test -z "$$files" || { \
+	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
+	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
+	    } \
+	; done
+
+uninstall-binPROGRAMS:
+	@$(NORMAL_UNINSTALL)
+	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
+	files=`for p in $$list; do echo "$$p"; done | \
+	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
+	      -e 's/$$/$(EXEEXT)/' \
+	`; \
+	test -n "$$list" || exit 0; \
+	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
+	cd "$(DESTDIR)$(bindir)" && rm -f $$files
+
+clean-binPROGRAMS:
+	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
+
+faketest$(EXEEXT): $(faketest_OBJECTS) $(faketest_DEPENDENCIES) $(EXTRA_faketest_DEPENDENCIES) 
+	@rm -f faketest$(EXEEXT)
+	$(AM_V_CCLD)$(faketest_LINK) $(faketest_OBJECTS) $(faketest_LDADD) $(LIBS)
 
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT)
@@ -554,6 +650,7 @@ distclean-compile:
 	-rm -f *.tab.c
 
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/base_backend.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/faketest-faketest.Po@am__quote@
 @AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/libMdsTestBackend_a-check_backend.Po@am__quote@
 
 .c.o:
@@ -585,6 +682,20 @@ libMdsTestBackend_a-check_backend.obj: check_backend.c
 @AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='check_backend.c' object='libMdsTestBackend_a-check_backend.obj' libtool=no @AMDEPBACKSLASH@
 @AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
 @am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libMdsTestBackend_a_CFLAGS) $(CFLAGS) -c -o libMdsTestBackend_a-check_backend.obj `if test -f 'check_backend.c'; then $(CYGPATH_W) 'check_backend.c'; else $(CYGPATH_W) '$(srcdir)/check_backend.c'; fi`
+
+faketest-faketest.o: faketest.c
+@am__fastdepCC_TRUE@	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(faketest_CFLAGS) $(CFLAGS) -MT faketest-faketest.o -MD -MP -MF $(DEPDIR)/faketest-faketest.Tpo -c -o faketest-faketest.o `test -f 'faketest.c' || echo '$(srcdir)/'`faketest.c
+@am__fastdepCC_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/faketest-faketest.Tpo $(DEPDIR)/faketest-faketest.Po
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='faketest.c' object='faketest-faketest.o' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(faketest_CFLAGS) $(CFLAGS) -c -o faketest-faketest.o `test -f 'faketest.c' || echo '$(srcdir)/'`faketest.c
+
+faketest-faketest.obj: faketest.c
+@am__fastdepCC_TRUE@	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(faketest_CFLAGS) $(CFLAGS) -MT faketest-faketest.obj -MD -MP -MF $(DEPDIR)/faketest-faketest.Tpo -c -o faketest-faketest.obj `if test -f 'faketest.c'; then $(CYGPATH_W) 'faketest.c'; else $(CYGPATH_W) '$(srcdir)/faketest.c'; fi`
+@am__fastdepCC_TRUE@	$(AM_V_at)$(am__mv) $(DEPDIR)/faketest-faketest.Tpo $(DEPDIR)/faketest-faketest.Po
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	$(AM_V_CC)source='faketest.c' object='faketest-faketest.obj' libtool=no @AMDEPBACKSLASH@
+@AMDEP_TRUE@@am__fastdepCC_FALSE@	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) @AMDEPBACKSLASH@
+@am__fastdepCC_FALSE@	$(AM_V_CC@am__nodep@)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(faketest_CFLAGS) $(CFLAGS) -c -o faketest-faketest.obj `if test -f 'faketest.c'; then $(CYGPATH_W) 'faketest.c'; else $(CYGPATH_W) '$(srcdir)/faketest.c'; fi`
 
 # This directory's subdirectories are mostly independent; you can cd
 # into them and run 'make' without going through this Makefile.
@@ -742,9 +853,12 @@ distdir: $(DISTFILES)
 	done
 check-am: all-am
 check: check-recursive
-all-am: Makefile $(LIBRARIES) all-local
+all-am: Makefile $(LIBRARIES) $(PROGRAMS) all-local
 installdirs: installdirs-recursive
 installdirs-am:
+	for dir in "$(DESTDIR)$(bindir)"; do \
+	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
+	done
 install: install-recursive
 install-exec: install-exec-recursive
 install-data: install-data-recursive
@@ -777,8 +891,8 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-recursive
 
-clean-am: clean-generic clean-local clean-noinstLIBRARIES \
-	mostlyclean-am
+clean-am: clean-binPROGRAMS clean-generic clean-local \
+	clean-noinstLIBRARIES mostlyclean-am
 
 distclean: distclean-recursive
 	-rm -rf ./$(DEPDIR)
@@ -804,7 +918,7 @@ install-dvi: install-dvi-recursive
 
 install-dvi-am:
 
-install-exec-am:
+install-exec-am: install-binPROGRAMS
 
 install-html: install-html-recursive
 
@@ -843,28 +957,77 @@ ps: ps-recursive
 
 ps-am:
 
-uninstall-am:
+uninstall-am: uninstall-binPROGRAMS
 
 .MAKE: $(am__recursive_targets) install-am install-strip
 
 .PHONY: $(am__recursive_targets) CTAGS GTAGS TAGS all all-am all-local \
-	check check-am clean clean-generic clean-local \
-	clean-noinstLIBRARIES cscopelist-am ctags ctags-am distclean \
-	distclean-compile distclean-generic distclean-tags distdir dvi \
-	dvi-am html html-am info info-am install install-am \
-	install-data install-data-am install-dvi install-dvi-am \
-	install-exec install-exec-am install-html install-html-am \
-	install-info install-info-am install-man install-pdf \
-	install-pdf-am install-ps install-ps-am install-strip \
-	installcheck installcheck-am installdirs installdirs-am \
-	maintainer-clean maintainer-clean-generic mostlyclean \
-	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
-	tags tags-am uninstall uninstall-am
+	check check-am clean clean-binPROGRAMS clean-generic \
+	clean-local clean-noinstLIBRARIES cscopelist-am ctags ctags-am \
+	distclean distclean-compile distclean-generic distclean-tags \
+	distdir dvi dvi-am html html-am info info-am install \
+	install-am install-binPROGRAMS install-data install-data-am \
+	install-dvi install-dvi-am install-exec install-exec-am \
+	install-html install-html-am install-info install-info-am \
+	install-man install-pdf install-pdf-am install-ps \
+	install-ps-am install-strip installcheck installcheck-am \
+	installdirs installdirs-am maintainer-clean \
+	maintainer-clean-generic mostlyclean mostlyclean-compile \
+	mostlyclean-generic pdf pdf-am ps ps-am tags tags-am uninstall \
+	uninstall-am uninstall-binPROGRAMS
 
 .PRECIOUS: Makefile
 
 
 include @top_builddir@/Makefile.inc
+
+#prova:
+#	echo $(TEST_LOGS);
+#	python -c "${_tap_py_execute}" pyex1;
+
+.PHONY: tap xml log
+tap: $(TEST_SUITE_TAP)
+xml: $(TEST_SUITE_XML)
+log: $(TEST_SUITE_LOG)
+
+tests:
+	echo "Making tests ... "
+	if [ -z ${TEST_FORMAT} ] ; then
+	 $(MAKE) $(AM_MAKEFLAGS) tap;
+	else
+	 $(MAKE) $(AM_MAKEFLAGS) $(TEST_FORMAT);
+	fi
+
+.ONESHELL:
+$(TEST_BUILD_TAP):
+	$(MAKE) -k $(AM_MAKEFLAGS) all;
+
+	echo "TAP version 13" > $@;
+	count=0;
+	for i in $(check_PROGRAMS); do \
+	  if ! $(MAKE) -q $$i; then \
+	    $(MAKE) -k $(AM_MAKEFLAGS) $$i || \
+	    { ((count++)); \
+	      echo "not ok $${count} - Build of $${i} failed." >> $@; \
+	    }; \
+	  fi; \
+	done; \
+	echo "1..$${count}" >> $@;
+
+.ONESHELL:
+$(TEST_SUITE_TAP): $(TEST_BUILD_TAP)
+	export TEST_FORMAT="tap";
+
+	$(MAKE) -k $(AM_MAKEFLAGS) $(TEST_LOGS) \
+	  PY_LOG_COMPILER="$(TAP_PY_LOG_COMPILER)" \
+	  PY_LOG_FLAGS="$(TAP_PY_LOG_FLAGS)";
+
+	perl ${top_srcdir}/testing/collate_tap.pl $(TEST_BUILD_TAP) $(TEST_LOGS) > $@ \
+	 || exit 1;
+
+.PHONY: clean-local-tests
+clean-local-tests:
+	-$(RM) -rf $(TEST_BUILD_TAP) $(TEST_SUITE_TAP)
 
 #
 # Shared library
@@ -873,7 +1036,6 @@ include @top_builddir@/Makefile.inc
 @MINGW_TRUE@ MAKE_IMPLIB_MdsTestShr=-Wl,--out-implib,@MAKELIBDIR@MdsTestShr.dll.a
 $(MdsTestShr): backends/check/libCheck.a libMdsTestBackend.a
 	$(CXX) $(TARGET_ARCH) $(CXXFLAGS) $(OUTPUT_OPTION) @LINKSHARED@ -Wl,-whole-archive $^ -Wl,-no-whole-archive $(LDFLAGS) $(LIBS) $(MAKE_IMPLIB_MdsTestShr)
-
 #               testing/selftest
 
 .ONESHELL:
