try to do tests after build ...

diff --git a/testing/Makefile.am b/testing/Makefile.am
--- a/testing/Makefile.am
+++ b/testing/Makefile.am
@@ -42,36 +42,43 @@ TEST_SUBDIRS = \
                mdsobjects/cpp/testing
 #              testing/selftest
 
+TEST_OUTDIR  ?= ${top_builddir}/testing
+
+.ONESHELL:
+print_outfiles:
+	@
+	echo $(TEST_OUTFILES);
+	echo $(TEST_OUTDIR);
 
 .ONESHELL:
 build_tests: $(MdsTestShr)
-	@ :; \
-	list='$(TEST_SUBDIRS)'; \
-	status=0; \
-	for subdir in $$list; do echo "Making in $$subdir"; \
-	 $(am__cd) ${top_builddir}/$${subdir} && $(MAKE) $(AM_MAKEFLAGS) tap || (( status |= 1)); \
-	 taps="$${taps} $${subdir}/$(TEST_SUITE_TAP)"; \
-	 ex_taps="$${ex_taps} $$(echo $${subdir} | sed 's|/|_|g').tap"; \
-	done; \
-	echo; \
-	echo " COMPONENTS WITH ERRORS FOUND: $${status} "; \
-	echo; \
-	echo " ------- COPYING TAP SUITES into ${top_builddir}/testing: ";\
-	$(am__cd) ${top_builddir}; \
-	for subdir in $$list; do \
-	 echo "$(INSTALL) $${subdir}/$(TEST_SUITE_TAP) testing/$$(echo $${subdir} | sed 's|/|_|g').tap;"; \
-	 $(INSTALL) $${subdir}/$(TEST_SUITE_TAP) testing/$$(echo $${subdir} | sed 's|/|_|g').tap; \
-	done; \
-	echo " -------- CUT HERE for Jenkins inclusion --------------- ";\
-	for i in $${taps}; do \
-	echo "$$i"; \
-	done; \
-	echo " ------------------------------------------------------- "; \
+	@
+	list='$(TEST_SUBDIRS)';
+	status=0;
+	for subdir in $$list; do echo "Making in $$subdir";
+	 $(am__cd) ${top_builddir}/$${subdir} && $(MAKE) $(AM_MAKEFLAGS) tap || (( status |= 1));
+	 taps="$${taps} $${subdir}/$(TEST_SUITE_TAP)";	 
+	done;
+	echo
+	echo " COMPONENTS WITH ERRORS FOUND: $${status} "
+	echo
+	echo " ------- SAVING TAP SUITES into ${TEST_OUTDIR}: "
+	$(am__cd) ${top_builddir};
+	$(MKDIR_P) ${TEST_OUTDIR};
+	for subdir in $$list; do 
+	 echo "$(INSTALL) $${subdir}/$(TEST_SUITE_TAP) ${TEST_OUTDIR}/$$(echo $${subdir} | sed 's|/|_|g').tap;";
+	 $(INSTALL) $${subdir}/$(TEST_SUITE_TAP) ${TEST_OUTDIR}/$$(echo $${subdir} | sed 's|/|_|g').tap;
+	done;
+	echo " -------- CUT HERE for Jenkins inclusion --------------- "
+	for i in $${taps}; do
+	echo "$$i"
+	done;
+	echo " ------------------------------------------------------- "
 	exit $${status}
 
 .ONESHELL:
 clean_tests: 
-	@ :; \
+	@
 	list='$(TEST_SUBDIRS)'; \
 	for subdir in $$list; do echo "Cleaning in $$subdir"; \
 	 $(am__cd) ${top_builddir}/$${subdir} && $(MAKE) $(AM_MAKEFLAGS) clean; \
diff --git a/testing/Makefile.in b/testing/Makefile.in
--- a/testing/Makefile.in
+++ b/testing/Makefile.in
@@ -519,6 +519,15 @@ _tap_py_execute = \
  tr.run(tests); 
 
 
+#prova:
+#	echo $(TEST_LOGS);
+#	python -c "${_tap_py_execute}" pyex1;
+
+# //////////////////////////////////////////////////////////////////////////// #
+# ///  select test form env variable  //////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+TEST_BUILDTYPE = local
+
 # //////////////////////////////////////////////////////////////////////////// #
 # ///  FILL TEST CHAIN  ////////////////////////////////////////////////////// #
 # //////////////////////////////////////////////////////////////////////////// #
@@ -941,18 +950,29 @@ uninstall-am:
 
 include @top_builddir@/Makefile.inc
 
-#prova:
-#	echo $(TEST_LOGS);
-#	python -c "${_tap_py_execute}" pyex1;
-
-# //////////////////////////////////////////////////////////////////////////// #
-# ///  select test form env variable  //////////////////////////////////////// #
-# //////////////////////////////////////////////////////////////////////////// #
-
 .PHONY: tap xml log
 tap: $(TEST_SUITE_TAP)
 xml: $(TEST_SUITE_XML)
 log: $(TEST_SUITE_LOG)
+
+define tests_config_dump
+echo 
+echo " ### CONFIGURATION DUMP: ###"
+echo 
+echo "  # test-suite related:";
+echo "  TEST_BUILDTYPE=${TEST_BUILDTYPE}";
+echo 
+echo "  # flags:";
+echo "  CFLAGS=\"${CFLAGS}\"";
+echo "  CXXFLAGS=\"${CXXFLAGS}\"";
+echo "  CPPFLAGS=\"${CPPFLAGS}\"";
+echo "  LDFLAGS=\"${LDFLAGS}\"";
+echo "  LIBS=\"${LIBS}\"";
+echo "  AM_LDFLAGS=\"${AM_LDFLAGS}\"";
+echo "  AM_LIBS=\"${AM_LIBS}\"";
+echo "  LDADD=\"${LDADD}\"";
+echo 
+endef
 
 tests:
 	echo "Making tests ... "
@@ -1017,35 +1037,43 @@ $(MdsTestShr): backends/check/libCheck.a libMdsTestBackend.a
 	$(CXX) $(TARGET_ARCH) $(CXXFLAGS) $(OUTPUT_OPTION) @LINKSHARED@ -Wl,-whole-archive $^ -Wl,-no-whole-archive $(LDFLAGS) $(LIBS) $(MAKE_IMPLIB_MdsTestShr)
 #              testing/selftest
 
+TEST_OUTDIR  ?= ${top_builddir}/testing
+
+.ONESHELL:
+print_outfiles:
+	@
+	echo $(TEST_OUTFILES);
+	echo $(TEST_OUTDIR);
+
 .ONESHELL:
 build_tests: $(MdsTestShr)
-	@ :; \
-	list='$(TEST_SUBDIRS)'; \
-	status=0; \
-	for subdir in $$list; do echo "Making in $$subdir"; \
-	 $(am__cd) ${top_builddir}/$${subdir} && $(MAKE) $(AM_MAKEFLAGS) tap || (( status |= 1)); \
-	 taps="$${taps} $${subdir}/$(TEST_SUITE_TAP)"; \
-	 ex_taps="$${ex_taps} $$(echo $${subdir} | sed 's|/|_|g').tap"; \
-	done; \
-	echo; \
-	echo " COMPONENTS WITH ERRORS FOUND: $${status} "; \
-	echo; \
-	echo " ------- COPYING TAP SUITES into ${top_builddir}/testing: ";\
-	$(am__cd) ${top_builddir}; \
-	for subdir in $$list; do \
-	 echo "$(INSTALL) $${subdir}/$(TEST_SUITE_TAP) testing/$$(echo $${subdir} | sed 's|/|_|g').tap;"; \
-	 $(INSTALL) $${subdir}/$(TEST_SUITE_TAP) testing/$$(echo $${subdir} | sed 's|/|_|g').tap; \
-	done; \
-	echo " -------- CUT HERE for Jenkins inclusion --------------- ";\
-	for i in $${taps}; do \
-	echo "$$i"; \
-	done; \
-	echo " ------------------------------------------------------- "; \
+	@
+	list='$(TEST_SUBDIRS)';
+	status=0;
+	for subdir in $$list; do echo "Making in $$subdir";
+	 $(am__cd) ${top_builddir}/$${subdir} && $(MAKE) $(AM_MAKEFLAGS) tap || (( status |= 1));
+	 taps="$${taps} $${subdir}/$(TEST_SUITE_TAP)";	 
+	done;
+	echo
+	echo " COMPONENTS WITH ERRORS FOUND: $${status} "
+	echo
+	echo " ------- SAVING TAP SUITES into ${TEST_OUTDIR}: "
+	$(am__cd) ${top_builddir};
+	$(MKDIR_P) ${TEST_OUTDIR};
+	for subdir in $$list; do 
+	 echo "$(INSTALL) $${subdir}/$(TEST_SUITE_TAP) ${TEST_OUTDIR}/$$(echo $${subdir} | sed 's|/|_|g').tap;";
+	 $(INSTALL) $${subdir}/$(TEST_SUITE_TAP) ${TEST_OUTDIR}/$$(echo $${subdir} | sed 's|/|_|g').tap;
+	done;
+	echo " -------- CUT HERE for Jenkins inclusion --------------- "
+	for i in $${taps}; do
+	echo "$$i"
+	done;
+	echo " ------------------------------------------------------- "
 	exit $${status}
 
 .ONESHELL:
 clean_tests: 
-	@ :; \
+	@
 	list='$(TEST_SUBDIRS)'; \
 	for subdir in $$list; do echo "Cleaning in $$subdir"; \
 	 $(am__cd) ${top_builddir}/$${subdir} && $(MAKE) $(AM_MAKEFLAGS) clean; \
