Update submodules even when running configure from another directory

diff --git a/conf/update_submodules b/conf/update_submodules
--- a/conf/update_submodules
+++ b/conf/update_submodules
@@ -3,11 +3,11 @@
 # update any submodules used by mdsplus
 #
 SUBMODULE_ERROR='Could not recursively update all git submodules. You may experience compilation problems if some submodules are out of date'
-SUBMODULE_OK='Git submodules updated successfully'
-if test -d .git; then \
-           (git submodule update --init --recursive && echo $SUBMODULE_OK) \
-        || (git submodule init && git submodule update --recursive && echo $SUBMODULE_OK) \
-        || (git submodule init && git submodule update && echo $SUBMODULE_ERROR) \
-        || (echo 'Git submodules could not be updated. Compilation will fail') \
+srcdir=$(dirname $0)/..
+if [ -r ${srcdir}/.git ]
+then
+  ( git -C $srcdir submodule --quiet update --init --recursive ) \
+    || ( git -C $srcdir submodule --quiet init && git submodule update --recursive ) \
+    || ( git -C $srcdir submodule --quiet init && git submodule update && echo $SUBMODULE_ERROR ) \
+    || (echo 'Git submodules could not be updated. Compilation will fail')
 fi
-
