debugging

diff --git a/deploy/jenkins_build b/deploy/jenkins_build
--- a/deploy/jenkins_build
+++ b/deploy/jenkins_build
@@ -495,7 +495,7 @@ build_windows() {
 	  tests_64=$?
 	  set -e
     fi
-    mkdir -p ${MDSPLUS_DIR};
+    popd
     mkdir -p ${WORKSPACE}/32;
     pushd ${WORKSPACE}/32;
     ${SRCDIR}/configure  \
@@ -517,16 +517,16 @@ build_windows() {
 	  tests_32=$?
 	  set -e
     fi
+    popd
     cd /winbld
     tmpdir=$(mktemp -d mdsplus-XXXXXXXXXX)
-    trap windows_cleanup EXIT
+#    trap windows_cleanup EXIT
     topsrcdir=${WINBLD_REMDIR}/${tmpdir}
     cd ${tmpdir}
     rsync -am --include="*/" --include="*.h*" --include="*.def" --exclude="*" ${SRCDIR}/ ./
     rsync -a ${SRCDIR}/mdsobjects/cpp ${SRCDIR}/mdsobjects/MdsObjects* ${SRCDIR}/mdsobjects/VS-* ./mdsobjects/
     rsync -a ${SRCDIR}/deploy/winbld.bat ./deploy/
     rsync -a ${MDSPLUS_DIR}/bin_* ./
-    echo curl http://${WINBLD_HOST}:8080${topsrcdir}/deploy/winbld.bat
     curl http://${WINBLD_HOST}:8080${topsrcdir}/deploy/winbld.bat
     # see if files are there
     ls /winbld/${tmpdir}/bin_x86*/*.lib /winbld/${tmpdir}/bin_x86*/MdsObjectsCppShr-VS.* > /dev/null
