Tests: added junit test for javatraverser2; TODO: fix StackOverflow in test_sqrtmultadd

diff --git a/javatraverser2/Makefile.in b/javatraverser2/Makefile.in
--- a/javatraverser2/Makefile.in
+++ b/javatraverser2/Makefile.in
@@ -14,6 +14,11 @@
 
 @SET_MAKE@
 
+# //////////////////////////////////////////////////////////////////////////// #
+# ///  TESTS SECTION   /////////////////////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+
 
 VPATH = @srcdir@
 am__is_gnu_make = { \
@@ -90,6 +95,15 @@ POST_UNINSTALL = :
 build_triplet = @build@
 host_triplet = @host@
 target_triplet = @target@
+@ENABLE_SANITIZE_TRUE@am__append_1 = ${ENABLE_SANITIZE_OPTIONS}=${${ENABLE_SANITIZE_OPTIONS}_SUPP}:${SAN_OPTIONS}:${${ENABLE_SANITIZE_OPTIONS}}:start_deactivated=1:exitcode=1 \
+@ENABLE_SANITIZE_TRUE@	LSAN_OPTIONS=${LSAN_OPTIONS_SUPP}:${LSAN_OPTIONS}:G_SLICE=always-malloc \
+@ENABLE_SANITIZE_TRUE@	TEST_LD_PRELOAD=${TEST_LD_PRELOAD} \
+@ENABLE_SANITIZE_TRUE@	TEST_TIMEUNIT=$$(($${TEST_TIMEUNIT:-1} * \
+@ENABLE_SANITIZE_TRUE@	5))
+@ENABLE_SANITIZE_TRUE@am__append_2 = $(shell ${_check_sanitize_ldd} || \
+@ENABLE_SANITIZE_TRUE@	echo --skip;) $(shell test \
+@ENABLE_SANITIZE_TRUE@	x"${ENABLE_SANITIZE}" != x"thread" || \
+@ENABLE_SANITIZE_TRUE@	echo --skip;)
 subdir = javatraverser2
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/ac_defun_local.m4 \
@@ -173,7 +187,8 @@ am__can_run_installinfo = \
 am__java_sources = $(java_JAVA)
 DATA = $(java_DATA)
 am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
-am__DIST_COMMON = $(srcdir)/Makefile.in
+am__DIST_COMMON = $(srcdir)/../testing/testing.am \
+	$(srcdir)/Makefile.in
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 ACLOCAL = @ACLOCAL@
 AMTAR = @AMTAR@
@@ -348,7 +363,7 @@ PYTHON_PLATFORM = @PYTHON_PLATFORM@
 PYTHON_PREFIX = @PYTHON_PREFIX@
 PYTHON_VERSION = @PYTHON_VERSION@
 PY_LOG_COMPILER = @PY_LOG_COMPILER@
-PY_LOG_FLAGS = @PY_LOG_FLAGS@
+PY_LOG_FLAGS = @PY_LOG_FLAGS@ $(am__append_2)
 RANLIB = @RANLIB@
 READLINE_CPPFLAGS = @READLINE_CPPFLAGS@
 READLINE_LDFLAGS = @READLINE_LDFLAGS@
@@ -379,7 +394,7 @@ SYBASE_LIB = @SYBASE_LIB@
 TARGET_ARCH = @TARGET_ARCH@
 TAR_EXCLUDE = @TAR_EXCLUDE@
 TDIC = @TDIC@
-TESTS_ENVIRONMENT = @TESTS_ENVIRONMENT@
+TESTS_ENVIRONMENT = @TESTS_ENVIRONMENT@ $(am__append_1)
 THREAD = @THREAD@
 UIL = @UIL@
 USE_PIPED_MESSAGING = @USE_PIPED_MESSAGING@
@@ -468,6 +483,29 @@ top_build_prefix = @top_build_prefix@
 top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 uiddir = @uiddir@
+TEST_CFLAGS = -I${top_srcdir}/testing
+TEST_LIBS = -lMdsTestShr @LIBM@ @THREAD@ @LIBRT@
+
+# ///  select test form env variable  //////////////////////////////////////// #
+TEST_BUILDTYPE = local
+SUFFIXES = .log .tap .xml
+.PRECIUS = %.log %.tap %.xml
+
+# // check if libpath is correct or skip python tests
+@ENABLE_SANITIZE_TRUE@_check_sanitize_ldd = \
+@ENABLE_SANITIZE_TRUE@   ( test "${ENABLE_SANITIZE}" != "no" -a -n "${ENABLE_SANITIZE_LIBPATH}" && \
+@ENABLE_SANITIZE_TRUE@     ldd ${MAKESHLIBDIR}/libMdsTestShr.so | grep ${ENABLE_SANITIZE_LIBPATH}  > /dev/null; )
+
+
+# //////////////////////////////////////////////////////////////////////////// #
+# ///  TAP TARGET   ////////////////////////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+
+# .PHONY: $(TEST_SUITE_TAP)
+TEST_BUILD_TAP = test-build.tap
+TEST_SUITE_TAP = test-suite.tap
+JAVA_LOG_COMPILER = java org.junit.runner.JUnitCore
+TEST_EXTENSIONS = $(test_SRC)
 EXTRA_DIST = 
 CLEANFILES = $(java_DATA) \
 	$(addprefix $(JAVAROOT)/,$(TRAV_CLS)) \
@@ -492,7 +530,7 @@ bin_SCRIPTS = $(JAVAROOT)
 
 #$(INSTALL) -D $< $@
 # Build the class files
-CLASSPATH_ENV = CLASSPATH=$(JSCH):$(JAVAROOT)
+CLASSPATH_ENV = CLASSPATH=$(JSCH):$(JAVAROOT):$(JUNIT)
 
 # Build the final jar
 JTRAVERSER_JAR = $(abs_builddir)/jTraverser.jar
@@ -500,10 +538,14 @@ TRAV_GIFS = $(addprefix ${srcdir}/java/,$(TRAV_GIF))
 java_SRC = $(TRAV_SRC) $(TOOLS_SRC) $(MDS_SRC)
 java_CLS = $(addprefix $(JAVAROOT)/,$(java_SRC:.java=.class))
 java_JAR = $(java_SRC:.java=*.class) $(TRAV_GIF)
+test_SRC = $(addprefix ${srcdir}/junit/,$(TEST_SRC))
+test_CLS = $(addprefix $(JAVAROOT)/,$(TEST_SRC:.java=.class))
+TEST_LOGS = $(test_CLS:.class=.log)
 JSCH = $(abs_srcdir)/jsch-0.1.54.jar
+JUNIT = $(top_srcdir)/testing/junit.jar
 MANIFEST = $(abs_builddir)/JTMANIFEST.mf
 @USE_JARS_DIR_FALSE@java_DATA = $(JTRAVERSER_JAR)
-@USE_JARS_DIR_FALSE@java_JAVA = $(addprefix ${srcdir}/java/,$(java_SRC) debug/DEBUG.java)
+@USE_JARS_DIR_FALSE@java_JAVA = $(addprefix ${srcdir}/java/,$(java_SRC) debug/DEBUG.java) $(test_SRC)
 
 # Giant list of source files follow
 TRAV_SRC = \
@@ -680,10 +722,23 @@ TRAV_GIF = \
 	jtraverser/text.gif \
 	jtraverser/window.gif
 
+TEST_SRC = \
+        mds/AllTests.java \
+        mds/MdsShr_Test.java \
+        mds/TreeShr_Test.java \
+        mds/data/CONST_Test.java \
+        mds/data/TREE_Test.java \
+        mds/data/descriptor/Descriptor_A_Test.java \
+        mds/data/descriptor/Descriptor_S_Test.java \
+        mds/data/descriptor_r/Function_Test.java
+
+test_path = $(abs_builddir)/trees
+hostfile = $(top_srcdir)/mdsobjects/python/tests/mdsip.hosts
 all: all-am
 
 .SUFFIXES:
-$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am  $(am__configure_deps)
+.SUFFIXES: .log .tap .xml
+$(srcdir)/Makefile.in: @MAINTAINER_MODE_TRUE@ $(srcdir)/Makefile.am $(srcdir)/../testing/testing.am $(am__configure_deps)
 	@for dep in $?; do \
 	  case '$(am__configure_deps)' in \
 	    *$$dep*) \
@@ -703,6 +758,7 @@ Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
 	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
 	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
 	esac;
+$(srcdir)/../testing/testing.am $(am__empty):
 
 $(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
 	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
@@ -956,6 +1012,176 @@ uninstall-am: uninstall-binSCRIPTS uninstall-javaDATA \
 
 .PRECIOUS: Makefile
 
+include @top_builddir@/Makefile.inc
+TEST_FORMAT     ?= log,tap
+AM_MAKEFLAGS    ?= V=0
+
+.PHONY: tap xml log
+tap: $(TEST_SUITE_TAP)
+xml: $(TEST_SUITE_XML)
+log: $(TEST_SUITE_LOG)
+
+.PHONY: rebuild-tests
+rebuild-tests:
+	@ \
+	if [ -n "$(check_PROGRAMS)" ]; then \
+	 echo "//// Rebuilding tests ////"; \
+	 rm -f *.$(OBJEXT); \
+	 rm -f $(check_PROGRAMS); \
+	 if [ -n "$${VALGRIND_BUILD}" ]; then \
+	  $(MAKE) -k $(AM_MAKEFLAGS) all ||:; \
+	 else \
+	  $(MAKE) -k $(AM_MAKEFLAGS) all \
+	  CFLAGS="${CFLAGS} -D_TESTING" CPPFLAGS="${CPPFLAGS} -D_TESTING" ||:; \
+	 fi; \
+	fi
+
+.PHONY: tests
+tests: rebuild-tests
+	@ \
+	echo "//// Performing tests /////"; \
+	export TEST_FORMAT=${TEST_FORMAT}; \
+	status=0; \
+	$(MAKE) -k $(AM_MAKEFLAGS) $(TEST_SUITE_LOG) || status=$$?;\
+	$(MAKE) -k $(AM_MAKEFLAGS) $${TEST_FORMAT//,/ } || status=$$?; \
+	exit $$status
+
+# //////////////////////////////////////////////////////////////////////////// #
+# ///  VALGRIND RULES  /////////////////////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+
+@VALGRIND_CHECK_RULES@
+
+# //////////////////////////////////////////////////////////////////////////// #
+# ///  SANITIZE RULES  /////////////////////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+
+@ENABLE_SANITIZE_TRUE@  # // sanitizer options specific (overload this in your Makefile.am) //
+@ENABLE_SANITIZE_TRUE@  LSAN_OPTIONS       ?=
+@ENABLE_SANITIZE_TRUE@  ASAN_OPTIONS       ?=
+@ENABLE_SANITIZE_TRUE@  TSAN_OPTIONS       ?=
+@ENABLE_SANITIZE_TRUE@  UBSAN_OPTIONS      ?=
+
+@ENABLE_SANITIZE_TRUE@  # // suppressions files (overload this in your Makefile.am) //
+@ENABLE_SANITIZE_TRUE@  LSAN_OPTIONS_SUPP  ?= suppressions=$(top_srcdir)/conf/gcc-lsan.supp
+@ENABLE_SANITIZE_TRUE@  ASAN_OPTIONS_SUPP  ?= suppressions=$(top_srcdir)/conf/gcc-asan.supp
+@ENABLE_SANITIZE_TRUE@  TSAN_OPTIONS_SUPP  ?= suppressions=$(top_srcdir)/conf/gcc-tsan.supp
+@ENABLE_SANITIZE_TRUE@  UBSAN_OPTIONS_SUPP ?= suppressions=$(top_srcdir)/conf/gcc-ubsan.supp
+
+@ENABLE_SANITIZE_TRUE@  # Preloaded libraries to be exported within the test-driver script. This was
+@ENABLE_SANITIZE_TRUE@  # done to avoid having libraries for 32bit preloaded when we trigger the
+@ENABLE_SANITIZE_TRUE@  # shell executable to run script. NOTE: This could harm a possible preload
+@ENABLE_SANITIZE_TRUE@  # order that we would add in the future ... maybe an AM_LD_PRELOAD should be
+@ENABLE_SANITIZE_TRUE@  # foreseen.
+@ENABLE_SANITIZE_TRUE@  #
+@ENABLE_SANITIZE_TRUE@  TEST_LD_PRELOAD    ?= ${ENABLE_SANITIZE_LIBPATH}
+
+@ENABLE_SANITIZE_TRUE@  # // NOTE:
+@ENABLE_SANITIZE_TRUE@  # somtimes thread sanitizer does not work with python... probably because of
+@ENABLE_SANITIZE_TRUE@  # the -fpie flag for now we will disable it at all.
+@ENABLE_SANITIZE_TRUE@  #
+
+# Single tap output
+# ^^^^^^^^^^^^^^^^^
+# Tap target to generate single tap result beside the normal log file. This
+# should make use of the TEST_TAPFILE env that generate multiple logger
+# instances.
+
+$(TEST_LOGS:.log=.tap):
+	@ \
+	f=$(@:.tap=.log); rm -f $$f; \
+	$(MAKE) $(AM_MAKEFLAGS) $$f TEST_TAPFILE=$@ ||:
+
+# Tap Test Build Suite
+# ^^^^^^^^^^^^^^^^^^^^
+# Collects the tap result of possible test build failures prior to make the
+# actual tests
+
+$(TEST_BUILD_TAP):
+	@ \
+	if [ -n "$(check_PROGRAMS)" ]; then \
+	 echo "Try to build targets one by one"; \
+	 echo "TAP version 13" > $@; \
+	 count=0; \
+	 for i in $(check_PROGRAMS); do \
+	  if ! $(MAKE) -q $$i; then \
+	    $(MAKE) -k $(AM_MAKEFLAGS) $$i || \
+	    { ((count++)); \
+	      echo "not ok $${count} - Build of $${i} failed." >> $@; \
+	    }; \
+	  fi; \
+	 done; \
+	fi; \
+	echo "1..$${count}" >> $@;
+
+# Tap Test Suite
+# ^^^^^^^^^^^^^^
+# The results are collected here using a perl script collate_tap.pl that is
+# using the perl tap parser from cpan. If it is not actually available
+# configure should have diabled HAVE_PL_TAP_PARSER.
+#
+# TODO: fix this in the case the only tap is provided as TEST_FORMAT and the
+# test taps are streamed into the .log file directly ... for now a workaround
+# was added: both TEST_LOGS and TEST_LOGS.tap are added to ${suite} so in both
+# cases it is able to collect results. remember to add $(TEST_LOGS:.log=.tap)
+# to prerequisites in the future when fix will be done.
+#
+
+$(TEST_SUITE_TAP): $(TEST_BUILD_TAP)
+@HAVE_PL_TAP_PARSER_TRUE@	@ ## collate test-build.tap \
+@HAVE_PL_TAP_PARSER_TRUE@	if [ -n "$(VALGRIND_TOOL)" ]; then suite="$@.$(VALGRIND_TOOL)"; \
+@HAVE_PL_TAP_PARSER_TRUE@	else suite="$@"; \
+@HAVE_PL_TAP_PARSER_TRUE@	fi; \
+@HAVE_PL_TAP_PARSER_TRUE@	perl $(top_srcdir)/testing/collate_tap.pl $(TEST_BUILD_TAP) \
+@HAVE_PL_TAP_PARSER_TRUE@	     $(TEST_LOGS) $(TEST_LOGS:.log=.tap) > $${suite} \
+@HAVE_PL_TAP_PARSER_TRUE@	     || exit 1
+@HAVE_PL_TAP_PARSER_FALSE@	@ ## test parser not available \
+@HAVE_PL_TAP_PARSER_FALSE@	echo "Can not collate tap results" >2;
+
+$(TEST_SUITE_XML):
+
+$(TEST_LOGS:.log=.xml): 
+	@ \
+	f=$(@:.xml=.log); rm -f $$f; \
+	$(MAKE) $(AM_MAKEFLAGS) $$f TEST_XMLFILE=$@ ||:s
+
+# //////////////////////////////////////////////////////////////////////////// #
+# ///  clean  //////////////////////////////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+
+.PHONY: clean-local-tests
+clean-local-tests:
+	-$(RM) -rf $(TEST_BUILD_TAP)
+	-$(RM) -rf $(TEST_SUITE_TAP)
+	-$(RM) -rf $(TEST_LOGS:.log=.tap)
+	-$(RM) -rf $(TEST_SUITE_XML)
+	-$(RM) -rf $(TEST_LOGS:.log=.xml)
+
+# //////////////////////////////////////////////////////////////////////////// #
+# ///  utils  //////////////////////////////////////////////////////////////// #
+# //////////////////////////////////////////////////////////////////////////// #
+
+.PHONY: tests-envdump
+tests-envdump:
+	@echo; \
+	echo ----------------------------------------------------------------; \
+	echo TESTS_ENVIRONMENT = ;\
+	for _i in ${TESTS_ENVIRONMENT}; do \
+	 echo "     $${_i}"; \
+	done;
+
+test-env:
+	for _i in ${TESTS_ENVIRONMENT}; do \
+	  export $${_i}; \
+	done; \
+	bash -i
+
+@HAVE_WINE_TRUE@wineconsole:
+@HAVE_WINE_TRUE@	@ \
+@HAVE_WINE_TRUE@	echo "--------------------------------------------------------------"; \
+@HAVE_WINE_TRUE@	echo "%PATH% = $(shell $${TESTS_ENVIRONMENT} wine cmd /c 'echo %PATH%' 2>/dev/null)"; \
+@HAVE_WINE_TRUE@	echo "--------------------------------------------------------------"; \
+@HAVE_WINE_TRUE@	${TESTS_ENVIRONMENT} wineconsole
 
 $(JAVAROOT):
 	mkdir -p $@
@@ -978,6 +1204,11 @@ $(MANIFEST): $(srcdir)/JTMANIFEST.mf
 @USE_JARS_DIR_FALSE@	pushd $(JAVAROOT) &&\
 @USE_JARS_DIR_FALSE@	$(JAR) u0fm "$@" $(MANIFEST) $(java_JAR) $(TRAV_GIF) &&\
 @USE_JARS_DIR_FALSE@	popd
+log: $(test_CLS)
+	mkdir $(test_path) && \
+	trap "$(RM) -r $(test_path)" EXIT && \
+	$(TEST_ENVIRONMENT) $(CLASSPATH_ENV) test_path=$(test_path) hostfile=$(hostfile) test_mdsip=0 $(JAVA_LOG_COMPILER)  mds.AllTests; \
+	$(TEST_ENVIRONMENT) $(CLASSPATH_ENV) test_path=$(test_path) hostfile=$(hostfile) test_mdsip=1 $(JAVA_LOG_COMPILER)  mds.AllTests;
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
